language: java
matrix:
  include:
  - jdk: openjdk9
  - jdk: openjdk11

os:
  - linux

install: mvn install

cache:
  directories:
  - $HOME/.m2

after_success:
- mvn clean test jacoco:report
- bash <(curl -Ls https://coverage.codacy.com/get.sh)
