language: java
matrix:
  include:
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12

os:
  - linux

install: mvn install

cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn clean test jacoco:report
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r snmpman/target/site/jacoco/jacoco.xml --partial
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r snmpman-cli/target/site/jacoco/jacoco.xml --partial
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) final
