language: java
matrix:
  include:
  - jdk: openjdk8
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: openjdk11

os:
  - linux

install: mvn install -Dgpg.skip

cache:
    directories:
    - $HOME/.m2
