# This release process looks for tags and produces releases.
name: Release

on:
  push:
    tags:
      - 'snmpman-parent-[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      md5sum: ${{ steps.md5sum.outputs.md5sum }}
      sha256sum: ${{ steps.sha256sum.outputs.sha256sum }}
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Extract current maven version
      run: echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      id: version
      shell: bash

    - name: Calculate MD5
      run: echo "::set-output name=md5sum::$(md5sum -b snmpman-cli/target/snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz | cut -f1 -d" ")"
      id: md5sum
      shell: bash

    - name: Calculate SHA256
      run: echo "::set-output name=sha256sum::$(sha256sum -b snmpman-cli/target/snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz | cut -f1 -d" ")"
      id: sha256sum
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz
        path: snmpman-cli/target/snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        body: |
          # Release ${{ steps.version.outputs.version }}
          ## Changes
          
          * 1
          * 2
          * 3

          ## Checksums
          |Type|Message digest|
          |----|--------------|
          |MD5|`${{ steps.md5sum.outputs.md5sum }}`|
          |SHA256|`${{ steps.sha256sum.outputs.sha256sum }}`|

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: snmpman-cli/target/snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz
        asset_name: snmpman-cli-${{ steps.version.outputs.version }}-bin.tar.gz
        asset_content_type: application/tar+gzip
